packages:
- '.'
resolver: lts-24.15

nix:
  packages:
    - cairo
    - gcc
    - pango
    - gtk3
    - hicolor-icon-theme
    - libdbusmenu
    - libdbusmenu-gtk3
    - libxml2
    - pkg-config
    - xorg.libX11
    - xorg.libXScrnSaver
    - xorg.libXext
    - xorg.libXinerama
    - xorg.libXrandr
    - xorg.libXrender
    - zlib
